/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new complaint case */
        post: operations["createCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{caseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get case detail */
        get: operations["getCase"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{caseId}/intake/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Append chat/intake message and run slot extraction */
        post: operations["appendIntakeMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{caseId}/decomposition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decompose complaint into routable nodes */
        post: operations["decomposeCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{caseId}/routing/recommendation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate routing recommendation with reasons */
        post: operations["recommendRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{caseId}/routing/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** User confirms selected routing option */
        post: operations["confirmRouteDecision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{caseId}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register evidence metadata after file upload */
        post: operations["registerEvidence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{caseId}/evidence/checklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get evidence sufficiency checklist */
        get: operations["getEvidenceChecklist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{caseId}/submission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit complaint to selected institution channel */
        post: operations["submitCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{caseId}/institution/mock-event": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply mock institution event to current submission */
        post: operations["applyInstitutionMockEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{caseId}/supplement-response": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Respond to institution supplement request */
        post: operations["respondSupplement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{caseId}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get full case timeline */
        get: operations["getTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        CaseStatus: "RECEIVED" | "CLASSIFIED" | "ROUTE_CONFIRMED" | "EVIDENCE_COLLECTING" | "MEDIATION_IN_PROGRESS" | "MEDIATION_SUCCESS" | "MEDIATION_FAILED" | "FORMAL_SUBMISSION_READY" | "INSTITUTION_PROCESSING" | "SUPPLEMENT_REQUIRED" | "COMPLETED" | "CLOSED";
        /** @enum {string} */
        RiskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        CreateCaseRequest: {
            /** @example INTER_FLOOR_NOISE */
            scenarioType: string;
            /** @enum {string} */
            housingType: "APARTMENT" | "MULTI_FAMILY" | "OFFICETEL" | "OTHER";
            consentAccepted: boolean;
            initialSummary?: string;
        };
        CaseSummary: {
            /** Format: uuid */
            caseId: string;
            status: components["schemas"]["CaseStatus"];
            riskLevel?: components["schemas"]["RiskLevel"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CaseDetail: components["schemas"]["CaseSummary"] & {
            intake?: components["schemas"]["IntakeSnapshot"];
            decomposition?: components["schemas"]["DecompositionResult"];
            routing?: components["schemas"]["RoutingRecommendation"];
            evidenceChecklist?: components["schemas"]["EvidenceChecklist"];
            currentActionRequired?: string;
        };
        IntakeSnapshot: {
            requiredSlots?: string[];
            filledSlots?: {
                [key: string]: unknown;
            };
            riskSignalDetected?: boolean;
        };
        AppendIntakeMessageRequest: {
            /** @enum {string} */
            role: "USER" | "AGENT";
            message: string;
        };
        IntakeUpdateResponse: {
            /** Format: uuid */
            caseId: string;
            status: components["schemas"]["CaseStatus"];
            intake: components["schemas"]["IntakeSnapshot"];
            recommendedFollowUpQuestion?: string;
            followUpInterface?: components["schemas"]["FollowUpInterface"];
        };
        /** @enum {string} */
        FollowUpInterfaceType: "OPTIONS" | "DATE";
        /** @enum {string} */
        FollowUpSelectionMode: "SINGLE" | "MULTIPLE";
        FollowUpOption: {
            optionId: string;
            label: string;
        };
        FollowUpInterface: {
            interfaceType: components["schemas"]["FollowUpInterfaceType"];
            selectionMode: components["schemas"]["FollowUpSelectionMode"];
            options: components["schemas"]["FollowUpOption"][];
        };
        DecompositionNode: {
            /** @enum {string} */
            nodeType: "LIVING_NOISE" | "IMMEDIATE_RISK" | "LONG_TERM_DISPUTE";
            title: string;
            priority: number;
            rationale?: string;
        };
        DecompositionResult: {
            /** Format: uuid */
            caseId: string;
            nodes: components["schemas"]["DecompositionNode"][];
        };
        RoutingOption: {
            optionId: string;
            /** @enum {string} */
            channelType: "EMERGENCY_112" | "MANAGEMENT_OFFICE" | "NEIGHBOR_CENTER" | "E_PEOPLE" | "DISPUTE_MEDIATION";
            label: string;
            priority: number;
            reason?: string;
            requiredEvidence?: string[];
        };
        RoutingRecommendation: {
            /** Format: uuid */
            caseId: string;
            options: components["schemas"]["RoutingOption"][];
            selectedOptionId?: string;
        };
        RouteDecisionRequest: {
            optionId: string;
            userConfirmed: boolean;
            note?: string;
        };
        RegisterEvidenceRequest: {
            /** @enum {string} */
            evidenceType: "AUDIO" | "LOG" | "IMAGE" | "DOCUMENT";
            storageKey: string;
            originalFileName?: string;
            mimeType?: string;
            sizeBytes?: number;
            /** Format: date-time */
            capturedAt: string;
            notes?: string;
        };
        EvidenceItem: {
            /** Format: uuid */
            evidenceId: string;
            evidenceType: string;
            storageKey: string;
            /** Format: date-time */
            uploadedAt: string;
            /** Format: float */
            adequacyScore?: number;
        };
        EvidenceChecklist: {
            isSufficient: boolean;
            missingItems: string[];
            guidance?: string;
        };
        SubmitCaseRequest: {
            /** @enum {string} */
            submissionChannel: "MCP_API" | "DIRECT_API" | "MANUAL_PDF";
            userConsent: boolean;
            identityVerified: boolean;
        };
        SubmissionResponse: {
            /** Format: uuid */
            caseId: string;
            submissionId: string;
            /** @enum {string} */
            submissionStatus: "QUEUED" | "SUBMITTED" | "FAILED";
            /** Format: date-time */
            submittedAt?: string;
        };
        SupplementResponseRequest: {
            message: string;
            evidenceIds?: string[];
        };
        /** @enum {string} */
        InstitutionMockEventType: "SUPPLEMENT_REQUIRED" | "COMPLETED";
        InstitutionMockEventRequest: {
            eventType: components["schemas"]["InstitutionMockEventType"];
            message?: string;
        };
        TimelineEvent: {
            /** Format: uuid */
            eventId: string;
            /** @enum {string} */
            eventType: "CASE_CREATED" | "RISK_DETECTED" | "CLASSIFICATION_DONE" | "ROUTE_RECOMMENDED" | "ROUTE_CONFIRMED" | "EVIDENCE_ADDED" | "SUBMISSION_STARTED" | "SUBMISSION_COMPLETED" | "SUPPLEMENT_REQUESTED" | "SUPPLEMENT_RESPONDED" | "CASE_COMPLETED";
            /** Format: date-time */
            occurredAt: string;
            title: string;
            description?: string;
            /** @enum {string} */
            actor?: "SYSTEM" | "USER" | "INSTITUTION";
        };
        TimelineResponse: {
            /** Format: uuid */
            caseId: string;
            events: components["schemas"]["TimelineEvent"][];
        };
        ApiError: {
            /** Format: date-time */
            timestamp: string;
            traceId: string;
            /** @example CASE_STATE_CONFLICT */
            code: string;
            message: string;
            details?: string[];
        };
    };
    responses: {
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Invalid state transition or duplicate action */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Upstream institution gateway unavailable */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        /** @description Correlation ID for tracing. */
        TraceId: string;
        /** @description Client-generated key to prevent duplicate processing. */
        IdempotencyKey: string;
        CaseId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createCase: {
        parameters: {
            query?: never;
            header?: {
                /** @description Correlation ID for tracing. */
                "X-Trace-Id"?: components["parameters"]["TraceId"];
                /** @description Client-generated key to prevent duplicate processing. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCaseRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getCase: {
        parameters: {
            query?: never;
            header?: {
                /** @description Correlation ID for tracing. */
                "X-Trace-Id"?: components["parameters"]["TraceId"];
            };
            path: {
                caseId: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    appendIntakeMessage: {
        parameters: {
            query?: never;
            header?: {
                /** @description Correlation ID for tracing. */
                "X-Trace-Id"?: components["parameters"]["TraceId"];
            };
            path: {
                caseId: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppendIntakeMessageRequest"];
            };
        };
        responses: {
            /** @description Updated intake status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeUpdateResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    decomposeCase: {
        parameters: {
            query?: never;
            header?: {
                /** @description Correlation ID for tracing. */
                "X-Trace-Id"?: components["parameters"]["TraceId"];
            };
            path: {
                caseId: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Decomposition result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecompositionResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    recommendRoute: {
        parameters: {
            query?: never;
            header?: {
                /** @description Correlation ID for tracing. */
                "X-Trace-Id"?: components["parameters"]["TraceId"];
            };
            path: {
                caseId: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recommendation generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutingRecommendation"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    confirmRouteDecision: {
        parameters: {
            query?: never;
            header?: {
                /** @description Correlation ID for tracing. */
                "X-Trace-Id"?: components["parameters"]["TraceId"];
            };
            path: {
                caseId: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteDecisionRequest"];
            };
        };
        responses: {
            /** @description Decision saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    registerEvidence: {
        parameters: {
            query?: never;
            header?: {
                /** @description Correlation ID for tracing. */
                "X-Trace-Id"?: components["parameters"]["TraceId"];
            };
            path: {
                caseId: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterEvidenceRequest"];
            };
        };
        responses: {
            /** @description Evidence item created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceItem"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getEvidenceChecklist: {
        parameters: {
            query?: never;
            header?: {
                /** @description Correlation ID for tracing. */
                "X-Trace-Id"?: components["parameters"]["TraceId"];
            };
            path: {
                caseId: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Checklist status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceChecklist"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    submitCase: {
        parameters: {
            query?: never;
            header?: {
                /** @description Correlation ID for tracing. */
                "X-Trace-Id"?: components["parameters"]["TraceId"];
                /** @description Client-generated key to prevent duplicate processing. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                caseId: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitCaseRequest"];
            };
        };
        responses: {
            /** @description Submission started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    applyInstitutionMockEvent: {
        parameters: {
            query?: never;
            header?: {
                /** @description Correlation ID for tracing. */
                "X-Trace-Id"?: components["parameters"]["TraceId"];
            };
            path: {
                caseId: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstitutionMockEventRequest"];
            };
        };
        responses: {
            /** @description Institution event applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    respondSupplement: {
        parameters: {
            query?: never;
            header?: {
                /** @description Correlation ID for tracing. */
                "X-Trace-Id"?: components["parameters"]["TraceId"];
            };
            path: {
                caseId: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplementResponseRequest"];
            };
        };
        responses: {
            /** @description Supplement response accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getTimeline: {
        parameters: {
            query?: never;
            header?: {
                /** @description Correlation ID for tracing. */
                "X-Trace-Id"?: components["parameters"]["TraceId"];
            };
            path: {
                caseId: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timeline events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
