name: civil_complaint_mobile_flutter
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/korea_gov24.transparent.png
  fonts:
    - family: "Pretendard GOV"
      fonts:
        - asset: assets/fonts/PretendardGOV-Thin.otf
          weight: 100
        - asset: assets/fonts/PretendardGOV-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/PretendardGOV-Light.otf
          weight: 300
        - asset: assets/fonts/PretendardGOV-Regular.otf
          weight: 400
        - asset: assets/fonts/PretendardGOV-Medium.otf
          weight: 500
        - asset: assets/fonts/PretendardGOV-SemiBold.otf
          weight: 600
        - asset: assets/fonts/PretendardGOV-Bold.otf
          weight: 700
        - asset: assets/fonts/PretendardGOV-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/PretendardGOV-Black.otf
          weight: 900
