export type CaseStatus =
  | 'RECEIVED'
  | 'CLASSIFIED'
  | 'ROUTE_CONFIRMED'
  | 'EVIDENCE_COLLECTING'
  | 'FORMAL_SUBMISSION_READY'
  | 'INSTITUTION_PROCESSING'
  | 'SUPPLEMENT_REQUIRED'
  | 'COMPLETED'
  | 'CLOSED';

export type ApiErrorCode =
  | 'VALIDATION_ERROR'
  | 'UNAUTHORIZED'
  | 'CASE_NOT_FOUND'
  | 'CASE_STATE_CONFLICT'
  | 'ROUTE_OPTION_NOT_FOUND'
  | 'INSTITUTION_GATEWAY_ERROR';
